// Auto-generated by bindgen from ghostty.h via build.rs.
// Do not edit manually — regenerated when ghostty.h changes.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/ghostty_sys.rs"));
